---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Restart httpd
      service: name=httpd state=restarted
      become: yes
- name: change hostname to myserver
  hostname:
    name: "webserver"